<div class="text-center mt-5 pb-5 pt-4">
		<h2 class="h1 m-0">
		<i class="fas fa-user-circle fa-2x mb-3"></i><br>
		<?= $_SESSION['nome'] ?>
	</h2>
	<small class="d-block text-muted"><?= $_SESSION['email'] ?></small>

	<div class="mt-5">
		<a href="/usuarios" class="btn btn-info btn-lg btn-login">Usuários <i class="fas fa-users ml-3" style="font-size: 14px"></i></a>

		<a href="/logout" class="btn btn-danger btn-lg btn-login">Logout <i class="fas fa-sign-out-alt ml-3" style="font-size: 14px"></i></a>
	</div>
</div>