
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <title>Teste Dev - <?= static::title($view) ?></title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <!-- Fontawesome -->
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css">
    <!-- Style -->
    <link rel="stylesheet" type="text/css" href="/css/style.css">

</head>

<body class="bg-light">
    <header>
        <nav class="navbar navbar-dark navbar-expand-lg">
            <div class="container">
                <h1><a href="/" class="navbar-brand">@<?= $_SESSION['nome'] ?></a></h1>
                <button type="button" class="d-block d-lg-none btn btn-toggle" data-toggle='collapse' data-target='#navbar-menu'>
                    <i class="fas fa-bars fa-lg text-white"></i>
                </button>
                <div class="navbar-collapse collapse" id="navbar-menu">
                    <ul class="navbar-nav ml-auto">

                        <li class="nav-item">
                            <a href="/" class="nav-link text-white">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a href="/dashboard" class="nav-link text-white">Dashboard</a>
                        </li>
                        <li class="nav-item">
                            <a href="/usuarios" class="nav-link text-white">Usuários</a>
                        </li>
                        <li class="nav-item">
                            <a href="/logout" class="btn btn-danger">Sair</a>
                        </li>

                    </ul>

                </div>
            </div>
        </nav>
    </header>
    <div class="container">

        <?php require_once "../App/Views/$view.phtml"; ?>

    </div>

    <!-- JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    <script src="/js/main.js"></script>
</body>

</html>